from .models import Coordinate, Request, Resource, Scenario


def build_sample_scenario() -> Scenario:
    return Scenario(
        resources=[
            Resource(
                id="tech-1",
                name="Asha",
                location=Coordinate(x=12, y=78),
                skills=["electrical", "inspection"],
                shift_start=8,
                shift_end=17,
            ),
            Resource(
                id="tech-2",
                name="Rohan",
                location=Coordinate(x=30, y=70),
                skills=["hvac", "inspection"],
                shift_start=9,
                shift_end=18,
            ),
            Resource(
                id="tech-3",
                name="Meera",
                location=Coordinate(x=58, y=62),
                skills=["plumbing", "inspection"],
                shift_start=8,
                shift_end=16,
            ),
            Resource(
                id="tech-4",
                name="Vikram",
                location=Coordinate(x=74, y=26),
                skills=["electrical", "hvac"],
                shift_start=10,
                shift_end=19,
            ),
            Resource(
                id="tech-5",
                name="Nina",
                location=Coordinate(x=44, y=20),
                skills=["plumbing", "electrical"],
                shift_start=7,
                shift_end=15,
            ),
        ],
        requests=[
            Request(
                id="job-1",
                title="Transformer inspection",
                location=Coordinate(x=18, y=68),
                required_skills=["electrical"],
                start_hour=9,
                end_hour=11,
                priority=5,
                estimated_duration=2,
            ),
            Request(
                id="job-2",
                title="Mall AC outage",
                location=Coordinate(x=38, y=74),
                required_skills=["hvac"],
                start_hour=10,
                end_hour=13,
                priority=4,
                estimated_duration=3,
            ),
            Request(
                id="job-3",
                title="Factory plumbing leak",
                location=Coordinate(x=63, y=56),
                required_skills=["plumbing"],
                start_hour=9,
                end_hour=12,
                priority=5,
                estimated_duration=2,
            ),
            Request(
                id="job-4",
                title="Retail audit visit",
                location=Coordinate(x=52, y=18),
                required_skills=["inspection"],
                start_hour=11,
                end_hour=14,
                priority=3,
                estimated_duration=2,
            ),
            Request(
                id="job-5",
                title="Warehouse backup power",
                location=Coordinate(x=80, y=34),
                required_skills=["electrical", "hvac"],
                start_hour=12,
                end_hour=16,
                priority=5,
                estimated_duration=3,
            ),
            Request(
                id="job-6",
                title="Clinic drainage issue",
                location=Coordinate(x=28, y=18),
                required_skills=["plumbing"],
                start_hour=8,
                end_hour=10,
                priority=2,
                estimated_duration=1,
            ),
        ],
    )
